version: '2'
services:


###############################
   cassandra0:
    build: .
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199
    environment:
      - CASSANDRA_SEEDS=cassandra0
      - CASSANDRA_CLUSTER_NAME=Test Cluster


###############################
   cassandra1:
    build: .
    container_name: cassandra1
    ports: 
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
    environment:
      - CASSANDRA_SEEDS=cassandra0
      - CASSANDRA_CLUSTER_NAME=Test Cluster